Description of bfstree
Home > matgraph > @graph > bfstree.m
bfstree
PURPOSE
bfstree(t,g,v) --- create a breadth-first spanning tree of g
SYNOPSIS
function bfstree(t,g,v)
DESCRIPTION
 bfstree(t,g,v) --- create a breadth-first spanning tree of g
 The tree is rooted a the vertex v (or vertex 1 if missing). If g is not
 connected, we generate a tree only for the component containing v;
 vertices in the other components are isolated vertices in t.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
copy_labels copy_labels(g,h) --- copy labels from h to g
embed embed --- create an embedding for a graph
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
hasxy hasxy(g) --- determine if an embedding has been created for g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
issparse issparse(g) --- check if g's adjacency matrix is sparse
neighbors neighbors(g,v) --- neighbors of v as a list.
nv nv(g) --- number of vertices in g
resize resize(g,n) --- change the number of vertices in g to n
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
SOURCE CODE
function bfstree(t,g,v)
% bfstree(t,g,v) --- create a breadth-first spanning tree of g
% The tree is rooted a the vertex v (or vertex 1 if missing). If g is not
% connected, we generate a tree only for the component containing v;
% vertices in the other components are isolated vertices in t.
if nargin==2
    v = 1;
end
n = nv(g);
if (v<0) || (v>n)
    error('Seed vertex out of range')
end
if (issparse(g))
    sparse(t)
end
resize(t,0);
resize(t,n);
q_init(n+1);
visited = zeros(n,1);
visited(v) = 1;
q_push(v);
while(q_size > 0)
    x = q_pop_front;
    nlist = neighbors(g,x);
    for w = nlist
        if (visited(w)==0)
            visited(w) = 1;
            add(t,x,w);
            q_push(w);
        end
    end
end
if hasxy(g)
    embed(t,getxy(g))
end
if is_labeled(g)
    copy_labels(t,g);
end