Description of circulant
Home > matgraph > @graph > circulant.m
circulant
PURPOSE
circulant(g,n,k) --- overwrite g with an n,k circulant graph
SYNOPSIS
function circulant(g,n,k)
DESCRIPTION
 circulant(g,n,k) --- overwrite g with an n,k circulant graph
 g has n vertices {1,2,...,n}. Each vertex has an edge to the next k in
 line. So this is a 2k regular graph.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
clear_edges clear_edges(g) --- delete all edges of g
resize resize(g,n) --- change the number of vertices in g to n
This function is called by:
SOURCE CODE
function circulant(g,n,k)
% circulant(g,n,k) --- overwrite g with an n,k circulant graph
% g has n vertices {1,2,...,n}. Each vertex has an edge to the next k in
% line. So this is a 2k regular graph.
resize(g,n);
clear_edges(g);
for u=1:n
    for uu=u+1:u+k
        v = mod(uu,n);
        if (v==0)
            v = n;
        end
        add(g,u,v);
    end
end