Description of clear_edges
Home > matgraph > @graph > clear_edges.m
clear_edges
PURPOSE
clear_edges(g) --- delete all edges of g
SYNOPSIS
function clear_edges(g)
DESCRIPTION
 clear_edges(g) --- delete all edges of g
CROSS-REFERENCE INFORMATION
This function calls:
issparse issparse(g) --- check if g's adjacency matrix is sparse
nv nv(g) --- number of vertices in g
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
circulant circulant(g,n,k) --- overwrite g with an n,k circulant graph
cube cube(g,k) --- create a k-cube (default k = 3)
dfstree dfstree(t,g,v) --- create a depth-first spanning tree of g
dodecahedron dodecahedron(g) --- overwrite g with the dodecahedron graph
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
icosahedron icosahedron(g) --- overwrite g with the icosahedron graph
interval_graph interval_graph(g,ilist) --- create an interval graph
line_graph line_graph(g,h) --- set g to be the line graph of h
octahedron octahedron(g) --- overwrite g with the octahedron graph, K(2,2,2)
random_regular random_regular(g,n,k) --- create a random regular graph
random_tree random_tree(t,n) --- overwrite t with a random tree on n vertices
selective selective(g,n,n0,d) --- selective attachment random graph
SOURCE CODE
function clear_edges(g)
% clear_edges(g) --- delete all edges of g
global GRAPH_MAGIC
n = nv(g);
if (issparse(g))
    GRAPH_MAGIC.graphs{g.idx}.array = ...
        logical(sparse([],[],[],n,n,0));
else
    GRAPH_MAGIC.graphs{g.idx}.array = false(n);
end