Description of clear_labels
Home > matgraph > @graph > clear_labels.m
clear_labels
PURPOSE
clear_labels(g) --- delete all labels in g
SYNOPSIS
function clear_labels(g)
DESCRIPTION
 clear_labels(g) --- delete all labels in g
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cayley cayley(g,perms) -- create a Cayley graph (undirected)
dot dot(g,filename) --- save graph for use by graphviz.
label Assign labels to vertices of g
random_bipartite random_bipartite(g,n,m,p) --- create a random bipartite graph
random_regular random_regular(g,n,k) --- create a random regular graph
SOURCE CODE
function clear_labels(g)
% clear_labels(g) --- delete all labels in g
global GRAPH_MAGIC;
% GRAPH_MAGIC.graphs{g.idx}.labels = cell(0);
if isfield(GRAPH_MAGIC.graphs{g.idx},'labels')
    GRAPH_MAGIC.graphs{g.idx} = ...
        rmfield(GRAPH_MAGIC.graphs{g.idx},'labels');
end