Description of components
Home > matgraph > @graph > components.m
components
PURPOSE
components(g) --- find the components of the graph g
SYNOPSIS
function p = components(g)
DESCRIPTION
 components(g) --- find the components of the graph g
 If g has n vertices, this returns a partition of the [n] based on the
 components of g.
CROSS-REFERENCE INFORMATION
This function calls:
component component(g,v) -- find vertices in v's component of g
nv nv(g) --- number of vertices in g
This function is called by:
bipartition part = bipartition(g) --- find bipartition of a bipartite graph
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
SUBFUNCTIONS
function p = ind2part(ind)
SOURCE CODE
function p = components(g)
% components(g) --- find the components of the graph g
% If g has n vertices, this returns a partition of the [n] based on the
% components of g.
n = nv(g);
indicator = zeros(n,1);
c = 0;
while (nnz(indicator)<n)
    c = c+1;
    % find first zero entry in indicator
    i = find(indicator==0);
    i = i(1);
    % get i's component
    ci = component(g,i);
    indicator(ci) = c;
end
%p = indicator;
p = ind2part(indicator);
function p = ind2part(ind)
% convert indicator vector to a partition
np = max(ind);
A = cell(np,1);
for k=1:np
    A{k} = find(ind == k);
end
p = partition(A);