Description of complement
Home > matgraph > @graph > complement.m
complement
PURPOSE
graph complement
SYNOPSIS
function complement(g,h)
DESCRIPTION
 graph complement
 complement(g) --- overwrite a graph with its own complement
 complement(g,h) --- overwrite g with the complement of h
CROSS-REFERENCE INFORMATION
This function calls:
copy copy(g,h) --- overwrite g with a copy of h
fast_set_matrix fast_set_matrix(g,A) --- overwrite the adjacency matrix of g with A
full full(g) --- convert internal storage for g to full
issparse issparse(g) --- check if g's adjacency matrix is sparse
matrix matrix(g) --- return (a copy of) the adjacency matrix of g
nv nv(g) --- number of vertices in g
This function is called by:
omega [w,S] = omega(g) --- clique number
SOURCE CODE
function complement(g,h)
% graph complement
% complement(g) --- overwrite a graph with its own complement
% complement(g,h) --- overwrite g with the complement of h
if nargin>1
    copy(g,h)
end
% complement only makes sense for full storage
if (issparse(g))
    full(g);
end
n = nv(g);
i = g.idx;
fast_set_matrix(g, ones(n) - eye(n) - matrix(g))