Description of component
Home > matgraph > @graph > component.m
component
PURPOSE
component(g,v) -- find vertices in v's component of g
SYNOPSIS
function vtcs = component(g,v)
DESCRIPTION
 component(g,v) -- find vertices in v's component of g
CROSS-REFERENCE INFORMATION
This function calls:
matrix matrix(g) --- return (a copy of) the adjacency matrix of g
nv nv(g) --- number of vertices in g
This function is called by:
components components(g) --- find the components of the graph g
SOURCE CODE
function vtcs = component(g,v)
% component(g,v) -- find vertices in v's component of g
n = nv(g);
if (v < 1) || (v>n)
    error('Vertex out of range')
end
vec = zeros(n,1);
vec(v) = 1;
A = matrix(g);
while(true)
    w = double(A*vec +vec > 0);
    if nnz(w) == nnz(vec)
        break
    end
    vec = w;
end
vtcs = find(vec);