Description of contract
Home > matgraph > @graph > contract.m
contract
PURPOSE
contract(g,u,v) --- contract v into u
SYNOPSIS
function contract(g,u,v)
DESCRIPTION
 contract(g,u,v) --- contract v into u
 All neighbors of v are added to the neighborhood of u,
 and then v is deleted. (When v is deleted, vertices that have higher
 index than v are renumbered.)
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
delete delete --- delete vertices or edges from a graph
neighbors neighbors(g,v) --- neighbors of v as a list.
nv nv(g) --- number of vertices in g
This function is called by:
SOURCE CODE
function contract(g,u,v)
% contract(g,u,v) --- contract v into u
% All neighbors of v are added to the neighborhood of u,
% and then v is deleted. (When v is deleted, vertices that have higher
% index than v are renumbered.)
n = nv(g);
if (u<0) || (u>n) || (v<0) || (v>n) || (u==v)
    return
end
nlist = neighbors(g,v);
for x = nlist;
    if (x ~= u)
        add(g,u,x)
    end
end
delete(g,v);