Description of copy_labels
Home > matgraph > @graph > copy_labels.m
copy_labels
PURPOSE
copy_labels(g,h) --- copy labels from h to g
SYNOPSIS
function copy_labels(g,h)
DESCRIPTION
 copy_labels(g,h) --- copy labels from h to g
CROSS-REFERENCE INFORMATION
This function calls:
get_label get_label(g) or get_label(g,v) --- get vertex label(s)
is_labeled is_labeled(g) --- determine if there are labels on vertices.
label Assign labels to vertices of g
nv nv(g) --- number of vertices in g
This function is called by:
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
dfstree dfstree(t,g,v) --- create a depth-first spanning tree of g
SOURCE CODE
function copy_labels(g,h)
% copy_labels(g,h) --- copy labels from h to g
if ~is_labeled(h)
    error('Source graph (2nd argument) must be labeled')
end
ng = nv(g);
nh = nv(h);
label(g);
for v=1:min(ng,nh)
    label(g,v,get_label(h,v));
end