Description of cube
Home > matgraph > @graph > cube.m
cube
PURPOSE
cube(g,k) --- create a k-cube (default k = 3)
SYNOPSIS
function cube(g,k)
DESCRIPTION
 cube(g,k) --- create a k-cube (default k = 3)
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
clear_edges clear_edges(g) --- delete all edges of g
complete complete: build complete and complete multipartite graphs
copy copy(g,h) --- overwrite g with a copy of h
cube cube(g,k) --- create a k-cube (default k = 3)
embed embed --- create an embedding for a graph
free free(g) --- free the graph from the system
full full(g) --- convert internal storage for g to full
graph graph: constructor for the graph class
path path(g,n) --- make g a path on n vertices
resize resize(g,n) --- change the number of vertices in g to n
This function is called by:
cube cube(g,k) --- create a k-cube (default k = 3)
SOURCE CODE
function cube(g,k)
% cube(g,k) --- create a k-cube (default k = 3)
if nargin==1
    cube(g,3);
    xy = [
        0   0
        1   0
        0   1
        1   1
        ];
    xy = [xy ; 2*xy-1/2];
    embed(g,xy);
    return
end
if (k==1)
    path(g,2);
    return
end
if (k==2)
    resize(g,4);
    clear_edges(g);
    full(g);
    elist = [ 1 2; 2 4; 4 3; 3 1];
    add(g,elist);
    xy = [ 0 0 ; 1 0 ; 0 1 ; 1 1];
    embed(g,xy);
    return
end
cube(g,k-1);
k2 = graph(2);
tmp = graph;
complete(k2);
embed(k2,[-1,0;1,0]);
copy(tmp,g);
cartesian(g,tmp,k2);
free(k2);
free(tmp);