Description of cycle
Home > matgraph > @graph > cycle.m
cycle
PURPOSE
cycle(g,n) --- create a cycle graph on n vertices
SYNOPSIS
function cycle(g,n)
DESCRIPTION
 cycle(g,n) --- create a cycle graph on n vertices
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
embed embed --- create an embedding for a graph
path path(g,n) --- make g a path on n vertices
This function is called by:
mobius mobius(g,nverts) --- create a Mobius ladder graph
wheel wheel(g,n) --- overwrite g with a wheel graph on n vertices
SOURCE CODE
function cycle(g,n)
% cycle(g,n) --- create a cycle graph on n vertices
path(g,n);
add(g,1,n);
embed(g);