Description of deg
Home > matgraph > @graph > deg.m
deg
PURPOSE
deg: degree of a vertex or degree sequence
SYNOPSIS
function d = deg(g,v)
DESCRIPTION
 deg: degree of a vertex or degree sequence
 deg(g) --- degree sequence of g
 deg(g,v) --- degree of v in g
CROSS-REFERENCE INFORMATION
This function calls:
full full(g) --- convert internal storage for g to full
This function is called by:
color color(g,algo) --- color the graph g by a given algorithm
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
laplacian laplacian(g) --- get the Laplacian matrix of g
nsptrees nsptrees(g) --- number of spanning trees of g.
prufer prufer --- convert a tree to/from its Prufer code
selective selective(g,n,n0,d) --- selective attachment random graph
thresh create a threshold graph, or test if g is a threshold graph
trim trim(g,d) --- iteratively remove vertices of degree at most d
vertex_degree_sequence find the degrees of the neighbors of a vertex
SOURCE CODE
function d = deg(g,v)
% deg: degree of a vertex or degree sequence
% deg(g) --- degree sequence of g
% deg(g,v) --- degree of v in g
global GRAPH_MAGIC
if (nargin==1)
    d = full(sum(GRAPH_MAGIC.graphs{g.idx}.array));
else
    d = full(sum(GRAPH_MAGIC.graphs{g.idx}.array(v,:)));
end