Description of disjoint_union
Home > matgraph > @graph > disjoint_union.m
disjoint_union
PURPOSE
disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
SYNOPSIS
function disjoint_union(g,h,k)
DESCRIPTION
 disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
 graphs h and k.
 If h and k both have embeddings, those embeddings are combined to form an
 embedding for g.
CROSS-REFERENCE INFORMATION
This function calls:
embed embed --- create an embedding for a graph
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
hasxy hasxy(g) --- determine if an embedding has been created for g
issparse issparse(g) --- check if g's adjacency matrix is sparse
make_logical make_logical(g) --- ensure that the internal storage for g's matrix is a
nv nv(g) --- number of vertices in g
rmxy rmxy(g) --- erase g's embedding
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
SOURCE CODE
function disjoint_union(g,h,k)
% disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
% graphs h and k.
% If h and k both have embeddings, those embeddings are combined to form an
% embedding for g.
global GRAPH_MAGIC
n1 = nv(h);
n2 = nv(k);
if (issparse(h) || issparse(k))
    z = logical(sparse([],[],[],n1,n2,0));
else
    z = false(n1,n2);
end
rmxy(g);
GRAPH_MAGIC.graphs{g.idx}.array = ...
    [GRAPH_MAGIC.graphs{h.idx}.array, z; ...
     z', GRAPH_MAGIC.graphs{k.idx}.array
    ];
make_logical(g);
if (hasxy(h) && hasxy(k))
    xy = [getxy(h);getxy(k)];
    embed(g,xy);
end