Description of edges
Home > matgraph > @graph > edges.m
edges
PURPOSE
edges(g) --- list the edges in g as a 2-column matrix
SYNOPSIS
function elist = edges(g)
DESCRIPTION
 edges(g) --- list the edges in g as a 2-column matrix
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bridges bridges(g,algo) --- find all cut edges in g
cayley cayley(g,perms) -- create a Cayley graph (undirected)
cdraw cdraw(g,coloring) -- draw g with a given vertex coloring
dot dot(g,filename) --- save graph for use by graphviz.
draw draw(g) --- draw g in a figure window
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
graffle graffle(g, filename, width, rad) --- write graph in OmniGraffle format
incidence_matrix incidence_matrix(g) --- return the vertex/edge incidence matrix.
line_graph line_graph(g,h) --- set g to be the line graph of h
prufer prufer --- convert a tree to/from its Prufer code
random_planar random_planar(g,n) --- create a random planar triangulation
save save(g,filename) --- save a graph to disk
sgf sgf --- simple graph format: a 2-column matrix representation
SOURCE CODE
function elist = edges(g)
% edges(g) --- list the edges in g as a 2-column matrix
global GRAPH_MAGIC
[i,j] = find(triu(GRAPH_MAGIC.graphs{g.idx}.array));
elist = [i,j];