Description of edge_color
Home > matgraph > @graph > edge_color.m
edge_color
PURPOSE
edge_color(g,algo) --- find a proper edge coloring of the graph g
SYNOPSIS
function c = edge_color(g,algo)
DESCRIPTION
 edge_color(g,algo) --- find a proper edge coloring of the graph g
 The returned matrix has three columns. Each row of this matrix of the
 form [i j c] where ij is an edge of the graph and c is a color number
 (from 1 to the number of colors used).
 algo denotes an algorithm. The choices are:
 greedy:    use a greedy coloring, based on the line graph (default)
 optimal:   create an optimal coloring, based on the line graph
 vizing:    create a coloring that uses at most max(deg(g))+1 colors
            NOTE: THIS IS UNIMPLEMENTED AT THIS TIME!
CROSS-REFERENCE INFORMATION
This function calls:
color color(g,algo) --- color the graph g by a given algorithm
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
edges edges(g) --- list the edges in g as a 2-column matrix
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
line_graph line_graph(g,h) --- set g to be the line graph of h
This function is called by:
cdraw cdraw(g,coloring) -- draw g with a given vertex coloring
draw draw(g) --- draw g in a figure window
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
SOURCE CODE
function c = edge_color(g,algo)
% edge_color(g,algo) --- find a proper edge coloring of the graph g
% The returned matrix has three columns. Each row of this matrix of the
% form [i j c] where ij is an edge of the graph and c is a color number
% (from 1 to the number of colors used).
%
% algo denotes an algorithm. The choices are:
%
% greedy:    use a greedy coloring, based on the line graph (default)
%
% optimal:   create an optimal coloring, based on the line graph
%
% vizing:    create a coloring that uses at most max(deg(g))+1 colors
%            NOTE: THIS IS UNIMPLEMENTED AT THIS TIME!
if nargin < 2
    algo = 'greedy';
end
switch (lower(algo))
    case {'greedy','optimal'}
        h = graph;
        line_graph(h,g);
        p = color(h,algo);
        c = [edges(g), array(p)'];
        free(h);
    case 'vizing'
        warning('edge_color:novizing',...
            'The "vizing" algorithm is not implemented. Using greedy algorithm.')
        c = edge_color(g,'greedy');
    otherwise
        error(['Unknown algorithm: ', algo]);
end