Description of eig
Home > matgraph > @graph > eig.m
eig
PURPOSE
eig(g) -- compute the eigenvalues of this graph
SYNOPSIS
function v = eig(g)
DESCRIPTION
 eig(g) -- compute the eigenvalues of this graph
 This returns the eigenvalues of the adjacency matrix of this graph.
 It's equivalent to eig(double(matrix(g)))
CROSS-REFERENCE INFORMATION
This function calls:
eig eig(g) -- compute the eigenvalues of this graph
matrix matrix(g) --- return (a copy of) the adjacency matrix of g
This function is called by:
eig eig(g) -- compute the eigenvalues of this graph
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
mdsxy mdsxy(g) -- create an embedding based on multidimensional scaling
split part = split(g) --- partition the vertices of g into two subsets
SOURCE CODE
function v = eig(g)
% eig(g) -- compute the eigenvalues of this graph
% This returns the eigenvalues of the adjacency matrix of this graph.
% It's equivalent to eig(double(matrix(g)))
v = eig(double(matrix(g)));