Description of fast_set_matrix
Home > matgraph > @graph > fast_set_matrix.m
fast_set_matrix
PURPOSE
fast_set_matrix(g,A) --- overwrite the adjacency matrix of g with A
SYNOPSIS
function fast_set_matrix(g,A)
DESCRIPTION
 fast_set_matrix(g,A) --- overwrite the adjacency matrix of g with A
 WARNING: No checks are done on the matrix!!! See set_matrix for a safer
 method. See also check_matrix.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
complement graph complement
complete complete: build complete and complete multipartite graphs
mycielski mycielski(g,n) --- create n'th order Mycielski graph (n > 0)
random random --- overwrite g with a random graph
random_bipartite random_bipartite(g,n,m,p) --- create a random bipartite graph
set_matrix set_matrix(g,A) --- set g to be the graph specificed in the matrix A.
SOURCE CODE
function fast_set_matrix(g,A)
% fast_set_matrix(g,A) --- overwrite the adjacency matrix of g with A
% WARNING: No checks are done on the matrix!!! See set_matrix for a safer
% method. See also check_matrix.
global GRAPH_MAGIC
GRAPH_MAGIC.graphs{g.idx}.array = logical(A);