Description of full
Home > matgraph > @graph > full.m
full
PURPOSE
full(g) --- convert internal storage for g to full
SYNOPSIS
function full(g)
DESCRIPTION
 full(g) --- convert internal storage for g to full
CROSS-REFERENCE INFORMATION
This function calls:
full full(g) --- convert internal storage for g to full
This function is called by:
add add --- add edge(s) to the graph
bridges bridges(g,algo) --- find all cut edges in g
bucky bucky(g) --- overwrite g with the Buckyball graph (and give a nice
complement graph complement
cube cube(g,k) --- create a k-cube (default k = 3)
deg deg: degree of a vertex or degree sequence
dodecahedron dodecahedron(g) --- overwrite g with the dodecahedron graph
full full(g) --- convert internal storage for g to full
graph graph: constructor for the graph class
icosahedron icosahedron(g) --- overwrite g with the icosahedron graph
load load(g,filename) --- read a saved graph on disk
octahedron octahedron(g) --- overwrite g with the octahedron graph, K(2,2,2)
petersen petersen(g) --- overwrite g with the Petersen graph
sgf sgf --- simple graph format: a 2-column matrix representation
subsref subsref implements the notation g(v) and g(v,w)
SOURCE CODE
function full(g)
% full(g) --- convert internal storage for g to full
global GRAPH_MAGIC
GRAPH_MAGIC.graphs{g.idx}.array = ...
    full(GRAPH_MAGIC.graphs{g.idx}.array);