Description of get_label
Home > matgraph > @graph > get_label.m
get_label
PURPOSE
get_label(g) or get_label(g,v) --- get vertex label(s)
SYNOPSIS
function out = get_label(g,v)
DESCRIPTION
 get_label(g) or get_label(g,v) --- get vertex label(s)
 get_label(g) returns a cell array of the labels of the vertices
 get_label(g,v) returns v's label
CROSS-REFERENCE INFORMATION
This function calls:
is_labeled is_labeled(g) --- determine if there are labels on vertices.
This function is called by:
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
copy_labels copy_labels(g,h) --- copy labels from h to g
dot dot(g,filename) --- save graph for use by graphviz.
draw_labels draw_labels(g) --- add labels to a drawing of g
save save(g,filename) --- save a graph to disk
SOURCE CODE
function out = get_label(g,v)
% get_label(g) or get_label(g,v) --- get vertex label(s)
% get_label(g) returns a cell array of the labels of the vertices
% get_label(g,v) returns v's label
global GRAPH_MAGIC;
if ~is_labeled(g)
    disp('graph is not labeled');
    out = {};
    if nargin==2
        out='';
    end
    return
end
if nargin==2
    out = GRAPH_MAGIC.graphs{g.idx}.labels{v};
    return
end
out = GRAPH_MAGIC.graphs{g.idx}.labels;