Description of graph
Home > matgraph > @graph > graph.m
graph
PURPOSE
graph: constructor for the graph class
SYNOPSIS
function g = graph(n)
DESCRIPTION
 graph: constructor for the graph class
 graph(n) --- create a new graph handle for a graph with n vertices
 graph(h) --- copy h into a new graph
 graph    --- create an empty graph
 graph(edge_list) --- create graph from n-by-2 list of edges
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
full full(g) --- convert internal storage for g to full
make_logical make_logical(g) --- ensure that the internal storage for g's matrix is a
size size(g) --- returns [nv,ne] for the graph
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
bridges bridges(g,algo) --- find all cut edges in g
cube cube(g,k) --- create a k-cube (default k = 3)
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
intersect intersect(g,h1,h2) --- g is set to the intersection of h1 and h2.
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
omega [w,S] = omega(g) --- clique number
prufer prufer --- convert a tree to/from its Prufer code
random_regular random_regular(g,n,k) --- create a random regular graph
union union(g,h1,h2) --- set g equal to the union of h1 and h2.
SOURCE CODE
function g = graph(n)
% graph: constructor for the graph class
% graph(n) --- create a new graph handle for a graph with n vertices
% graph(h) --- copy h into a new graph
% graph    --- create an empty graph
% graph(edge_list) --- create graph from n-by-2 list of edges
% make sure system has been initialized
if ~graph_system_exists
   graph_init;
end
global GRAPH_MAGIC;
% get a slot to store this graph
idx = find_available;
if (idx == 0)
    error('Graph system memory is full; cannot create new graph');
end
% default number of vertices is 0
if (nargin==0)
    n = 0;
end
% if n is a graph, then we perform a copy ...
if (isa(n,'graph'))
    GRAPH_MAGIC.in_use(idx) = 1;
    GRAPH_MAGIC.graphs{idx} = GRAPH_MAGIC.graphs{n.idx};
    g.idx = idx;
    g = class(g,'graph');
    make_logical(g);
    return
end
% ... otherwise we create a new graph
[nr,nc] = size(n);
if (nc > 2)
    error('Graph constructor argument is wrong shape')
end
if (nc==2)
    v = max(max(n));
    GRAPH_MAGIC.in_use(idx) = 1;
    GRAPH_MAGIC.graphs{idx}.array = logical(sparse([],[],[],v,v,1));
     g.idx = idx;
    g = class(g,'graph');
    if (v <= GRAPH_MAGIC.large_size)
        full(g);
    end
    add(g,n);
    return
end
GRAPH_MAGIC.in_use(idx) = 1;
GRAPH_MAGIC.graphs{idx}.array = logical(sparse([],[],[],n,n,n));
g.idx = idx;
g = class(g,'graph');
% if the graph is "small" enough, convert to full storage
if (n < GRAPH_MAGIC.large_size)
    full(g)
end
make_logical(g);