Description of has
Home > matgraph > @graph > has.m
has
PURPOSE
has --- check if the graph has a particular vertex or edge
SYNOPSIS
function yn = has(g,u,v)
DESCRIPTION
 has --- check if the graph has a particular vertex or edge
 has(g,u) --- check if g contains the vertex u
 has(g,u,v) --- check if g contains the edge uv
CROSS-REFERENCE INFORMATION
This function calls:
nv nv(g) --- number of vertices in g
This function is called by:
bridges bridges(g,algo) --- find all cut edges in g
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
springxy springxy(g) --- find a spring embedding of g
SOURCE CODE
function yn = has(g,u,v)
% has --- check if the graph has a particular vertex or edge
% has(g,u) --- check if g contains the vertex u
% has(g,u,v) --- check if g contains the edge uv
global GRAPH_MAGIC;
n = nv(g);
if (nargin==2)
    yn = (u>0) & (u<=n);
else
    if (u<0) || (u>n) || (v<0) || (v>n) || (u==v)
        yn = 0;
    else
        yn = GRAPH_MAGIC.graphs{g.idx}.array(u,v);
    end
end