Description of interval_graph
Home > matgraph > @graph > interval_graph.m
interval_graph
PURPOSE
interval_graph(g,ilist) --- create an interval graph
SYNOPSIS
function interval_graph(g,ilist)
DESCRIPTION
 interval_graph(g,ilist) --- create an interval graph
 ilist is an n-by-2 list of intervals.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
clear_edges clear_edges(g) --- delete all edges of g
renumber renumber the vertices of a graph
resize resize(g,n) --- change the number of vertices in g to n
rmxy rmxy(g) --- erase g's embedding
size size(g) --- returns [nv,ne] for the graph
This function is called by:
SUBFUNCTIONS
function yn = meets(a,b)
SOURCE CODE
function interval_graph(g,ilist)
% interval_graph(g,ilist) --- create an interval graph
% ilist is an n-by-2 list of intervals.
[n,x] = size(ilist);
for i=1:n
    ilist(i,:) = sort(ilist(i,:));
end
[ilist,idx] = sortrows(ilist);
resize(g,n);
clear_edges(g);
rmxy(g);
for i=1:n-1
    a = ilist(i,:);
    for j=i+1:n
        b = ilist(j,:);
        if (meets(a,b))
            add(g,i,j);
        end
        if a(2) < b(1)
            break
        end
    end
end
renumber(g,idx);
function yn = meets(a,b)
if (a(2) < b(1)) || (b(2) < a(1))
    yn = 0;
else
    yn = 1;
end