Description of is_labeled
Home > matgraph > @graph > is_labeled.m
is_labeled
PURPOSE
is_labeled(g) --- determine if there are labels on vertices.
SYNOPSIS
function yn = is_labeled(g)
DESCRIPTION
 is_labeled(g) --- determine if there are labels on vertices.
 By definition, an empty graph is NOT labeled.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
copy_labels copy_labels(g,h) --- copy labels from h to g
delete delete --- delete vertices or edges from a graph
dfstree dfstree(t,g,v) --- create a depth-first spanning tree of g
dot dot(g,filename) --- save graph for use by graphviz.
draw_labels draw_labels(g) --- add labels to a drawing of g
get_label get_label(g) or get_label(g,v) --- get vertex label(s)
induce induce --- create induced subgraphs
label Assign labels to vertices of g
ldraw ldraw(g,line_style) --- draw a graph with vertices marked with their labels
renumber renumber the vertices of a graph
resize resize(g,n) --- change the number of vertices in g to n
save save(g,filename) --- save a graph to disk
SOURCE CODE
function yn = is_labeled(g)
% is_labeled(g) --- determine if there are labels on vertices.
% By definition, an empty graph is NOT labeled.
global GRAPH_MAGIC
if (isfield(GRAPH_MAGIC.graphs{g.idx},'labels'))
    yn = length(GRAPH_MAGIC.graphs{g.idx}.labels) > 0;
else
    yn = false;
end