Description of isconnected
Home > matgraph > @graph > isconnected.m
isconnected
PURPOSE
isconnected(g) --- test if g is a connected graph
SYNOPSIS
function yn = isconnected(g)
DESCRIPTION
 isconnected(g) --- test if g is a connected graph
CROSS-REFERENCE INFORMATION
This function calls:
nv nv(g) --- number of vertices in g
This function is called by:
prufer prufer --- convert a tree to/from its Prufer code
resistance R = resistance(g) --- calculate resistances between vertices
springxy springxy(g) --- find a spring embedding of g
SOURCE CODE
function yn = isconnected(g)
% isconnected(g) --- test if g is a connected graph
global GRAPH_MAGIC
n = nv(g);
if (n==0)
    yn = 1;
    return
end
x = zeros(n,1);
x(1) = 1;
while(1)
    y = x;
    x = GRAPH_MAGIC.graphs{g.idx}.array*x + x;
    x = double(x>0);
    if (x==y)
        break
    end
end
yn = sum(x)==n;