Description of issparse
Home > matgraph > @graph > issparse.m
issparse
PURPOSE
issparse(g) --- check if g's adjacency matrix is sparse
SYNOPSIS
function yn = issparse(g)
DESCRIPTION
 issparse(g) --- check if g's adjacency matrix is sparse
CROSS-REFERENCE INFORMATION
This function calls:
issparse issparse(g) --- check if g's adjacency matrix is sparse
This function is called by:
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
clear_edges clear_edges(g) --- delete all edges of g
complement graph complement
disjoint_union disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
isfull isfull(g) --- check if g's adjacency matrix is full
issparse issparse(g) --- check if g's adjacency matrix is sparse
save save(g,filename) --- save a graph to disk
SOURCE CODE
function yn = issparse(g)
% issparse(g) --- check if g's adjacency matrix is sparse
global GRAPH_MAGIC
yn = issparse(GRAPH_MAGIC.graphs{g.idx}.array);