Description of label
Home > matgraph > @graph > label.m
label
PURPOSE
Assign labels to vertices of g
SYNOPSIS
function label(g,v,name)
DESCRIPTION
 Assign labels to vertices of g
 With no arguments, we assign default names for vertices (string versions
 of the vertex numbers)
 label(g,v,name) gives vertex v the name in the string name.
 label(g,vnamelist) assigns names to vertices in the cell array vlist
CROSS-REFERENCE INFORMATION
This function calls:
clear_labels clear_labels(g) --- delete all labels in g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
label Assign labels to vertices of g
nv nv(g) --- number of vertices in g
This function is called by:
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
cayley cayley(g,perms) -- create a Cayley graph (undirected)
copy_labels copy_labels(g,h) --- copy labels from h to g
dot dot(g,filename) --- save graph for use by graphviz.
draw_labels draw_labels(g) --- add labels to a drawing of g
induce induce --- create induced subgraphs
label Assign labels to vertices of g
load load(g,filename) --- read a saved graph on disk
shiftgraph shiftgraph(g,k,t) -- create a shiftgraph g based on t-tuples of k symbols
sl2graph sl2graph(g,p) -- create an SL(2,p) graph
SOURCE CODE
function label(g,v,name)
% Assign labels to vertices of g
% With no arguments, we assign default names for vertices (string versions
% of the vertex numbers)
% label(g,v,name) gives vertex v the name in the string name.
% label(g,vnamelist) assigns names to vertices in the cell array vlist
global GRAPH_MAGIC;
n = nv(g);
i = g.idx;
if nargin == 1
    clear_labels(g);
    GRAPH_MAGIC.graphs{i}.labels = cell(n,1);
    for v=1:n
        GRAPH_MAGIC.graphs{i}.labels{v} = int2str(v);
    end
    return
end
if nargin == 2
    clear_labels(g);
    GRAPH_MAGIC.graphs{i}.labels = v;
    return
end
if ~is_labeled(g)
    label(g);
end
if (v<0) || (v>n)
    error('No such vertex to label')
end
GRAPH_MAGIC.graphs{i}.labels{v} = name;