Description of ldraw
Home > matgraph > @graph > ldraw.m
ldraw
PURPOSE
ldraw(g,line_style) --- draw a graph with vertices marked with their labels
SYNOPSIS
function ldraw(g,line_style)
DESCRIPTION
 ldraw(g,line_style) --- draw a graph with vertices marked with their labels
 If the graph is unlabled, we use the vertex numbers instead.
 See also draw, cdraw, and ndraw.
CROSS-REFERENCE INFORMATION
This function calls:
draw draw(g) --- draw g in a figure window
draw_labels draw_labels(g) --- add labels to a drawing of g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
ndraw ndraw(g) --- draw g in a figure window with numbered vertices
This function is called by:
SOURCE CODE
function ldraw(g,line_style)
% ldraw(g,line_style) --- draw a graph with vertices marked with their labels
% If the graph is unlabled, we use the vertex numbers instead.
% See also draw, cdraw, and ndraw.
if ~is_labeled(g)
    if nargin ==1
        ndraw(g);
        return
    else
        ndraw(g,line_style)
        return
    end
end
if nargin == 1
    draw(g);
else
    draw(g,line_style);
end
draw_labels(g);