Description of line_graph
Home > matgraph > @graph > line_graph.m
line_graph
PURPOSE
line_graph(g,h) --- set g to be the line graph of h
SYNOPSIS
function line_graph(g,h)
DESCRIPTION
 line_graph(g,h) --- set g to be the line graph of h
 The line graph of h is the intersection graph of its edges.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
clear_edges clear_edges(g) --- delete all edges of g
edges edges(g) --- list the edges in g as a 2-column matrix
embed embed --- create an embedding for a graph
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
hasxy hasxy(g) --- determine if an embedding has been created for g
resize resize(g,n) --- change the number of vertices in g to n
rmxy rmxy(g) --- erase g's embedding
size size(g) --- returns [nv,ne] for the graph
This function is called by:
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
SUBFUNCTIONS
function yn = common_endpoint(e1,e2)
SOURCE CODE
function line_graph(g,h)
% line_graph(g,h) --- set g to be the line graph of h
% The line graph of h is the intersection graph of its edges.
elist = sortrows(edges(h));
[m,c] = size(elist);
resize(g,m);
rmxy(g);
clear_edges(g);
for i=1:m-1;
    a = elist(i,:);
    for j=i+1:m
        b = elist(j,:);
        if common_endpoint(a,b)
            add(g,i,j);
        end
        if (a(2) < b(1))
            break
        end
    end
end
if hasxy(h)
    xy = getxy(h);
    gxy = zeros(m,2);
    for i=1:m
        a = elist(i,1);
        b = elist(i,2);
        gxy(i,:) = (xy(a,:) + xy(b,:))/2;
    end
    embed(g,gxy);
end
function yn = common_endpoint(e1,e2)
yn = (e1(1) == e2(1)) | (e1(1) == e2(2)) | (e1(2) == e2(1)) | ...
    (e1(2) == e2(2));