Description of load
Home > matgraph > @graph > load.m
load
PURPOSE
load(g,filename) --- read a saved graph on disk
SYNOPSIS
function load(g,filename)
DESCRIPTION
 load(g,filename) --- read a saved graph on disk
 reads in a graph saved by a previous call to save(g,filename)
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
embed embed --- create an embedding for a graph
full full(g) --- convert internal storage for g to full
label Assign labels to vertices of g
nv nv(g) --- number of vertices in g
resize resize(g,n) --- change the number of vertices in g to n
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
SOURCE CODE
function load(g,filename)
% load(g,filename) --- read a saved graph on disk
% reads in a graph saved by a previous call to save(g,filename)
fid = fopen(filename,'r');
if fid == -1
    error(['File "', filename, '" cannot be opened for reading']);
end
A = textscan(fid,'%s\n','whitespace','\n');
A = A{1};
nl = length(A);
for k=1:nl
    line = A{k};
    eval(line);
end
resize(g,0);
if (sp == 1)
    sparse(g)
else
    full(g)
end
resize(g,nverts);
add(g,elist);
if (length(xy) > 0)
    embed(g,xy);
end
n = nv(g);
if (length(labs)>0)
    for k=1:n
        label(g,k,labs{k});
    end
end
fclose(fid);