Description of make_logical
Home > matgraph > @graph > make_logical.m
make_logical
PURPOSE
make_logical(g) --- ensure that the internal storage for g's matrix is a
SYNOPSIS
function make_logical(g)
DESCRIPTION
 make_logical(g) --- ensure that the internal storage for g's matrix is a
 logical matrix (for space efficiency).
 This function is called by various matgraph routines and it should not
 be necessary to call this in ordinary use of matgraph.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
disjoint_union disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
graph graph: constructor for the graph class
renumber renumber the vertices of a graph
resize resize(g,n) --- change the number of vertices in g to n
SOURCE CODE
function make_logical(g)
% make_logical(g) --- ensure that the internal storage for g's matrix is a
% logical matrix (for space efficiency).
% This function is called by various matgraph routines and it should not
% be necessary to call this in ordinary use of matgraph.
global GRAPH_MAGIC
if (~islogical(GRAPH_MAGIC.graphs{g.idx}.array))
    GRAPH_MAGIC.graphs{g.idx}.array = ...
        logical(GRAPH_MAGIC.graphs{g.idx}.array);
end