Description of matrix
Home > matgraph > @graph > matrix.m
matrix
PURPOSE
matrix(g) --- return (a copy of) the adjacency matrix of g
SYNOPSIS
function A = matrix(g)
DESCRIPTION
 matrix(g) --- return (a copy of) the adjacency matrix of g
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
across across(g,X,Y) --- find all edges with one end in X and other end in Y.
bipartition part = bipartition(g) --- find bipartition of a bipartite graph
bipmatch bipmatch --- maximum matching in a bipartite graph
chromatic_poly chrompoly(g) --- find the chromatic polynomial of g
complement graph complement
component component(g,v) -- find vertices in v's component of g
dist dist(g,v,w) and dist(g,v) --- find distance(s) between vertices
dom [d,S] = dom(g) --- domination number of g
eig eig(g) -- compute the eigenvalues of this graph
intersect intersect(g,h1,h2) --- g is set to the intersection of h1 and h2.
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
laplacian laplacian(g) --- get the Laplacian matrix of g
match_join match_join(g,h1,h2) --- overwrite g with a graph formed from disjoint
mycielski mycielski(g,n) --- create n'th order Mycielski graph (n > 0)
nsptrees nsptrees(g) --- number of spanning trees of g.
union union(g,h1,h2) --- set g equal to the union of h1 and h2.
SOURCE CODE
function A = matrix(g)
% matrix(g) --- return (a copy of) the adjacency matrix of g
global GRAPH_MAGIC
A = GRAPH_MAGIC.graphs{g.idx}.array;