Description of ndraw
Home > matgraph > @graph > ndraw.m
ndraw
PURPOSE
ndraw(g) --- draw g in a figure window with numbered vertices
SYNOPSIS
function ndraw(g,line_style)
DESCRIPTION
 ndraw(g) --- draw g in a figure window with numbered vertices
 ndraw(g,line_style) --- lines have given line_style
 see also draw, ldraw, and cdraw
CROSS-REFERENCE INFORMATION
This function calls:
draw draw(g) --- draw g in a figure window
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
nv nv(g) --- number of vertices in g
This function is called by:
ldraw ldraw(g,line_style) --- draw a graph with vertices marked with their labels
SOURCE CODE
function ndraw(g,line_style)
% ndraw(g) --- draw g in a figure window with numbered vertices
% ndraw(g,line_style) --- lines have given line_style
% see also draw, ldraw, and cdraw
if nargin == 1
    draw(g);
else
    draw(g,line_style);
end
xy = getxy(g);
n = nv(g);
for v=1:n
    x = xy(v,1);
    y = xy(v,2);
    text(x-.05,y,int2str(v));
end