Description of ne
Home > matgraph > @graph > ne.m
ne
PURPOSE
ne(g) --- number of edges in g or ne(g,h) --- check for inequality
SYNOPSIS
function m = ne(g,h)
DESCRIPTION
 ne(g) --- number of edges in g or ne(g,h) --- check for inequality
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
This function is called by:
bipartition part = bipartition(g) --- find bipartition of a bipartite graph
bridges bridges(g,algo) --- find all cut edges in g
cdraw cdraw(g,coloring) -- draw g with a given vertex coloring
display display(g) --- display basic information about a graph object
dot dot(g,filename) --- save graph for use by graphviz.
draw draw(g) --- draw g in a figure window
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
graffle graffle(g, filename, width, rad) --- write graph in OmniGraffle format
prufer prufer --- convert a tree to/from its Prufer code
random_regular random_regular(g,n,k) --- create a random regular graph
save save(g,filename) --- save a graph to disk
sgf sgf --- simple graph format: a 2-column matrix representation
size size(g) --- returns [nv,ne] for the graph
SOURCE CODE
function m = ne(g,h)
% ne(g) --- number of edges in g or ne(g,h) --- check for inequality
global GRAPH_MAGIC
if (nargin == 2)
    if any(size(g) ~= size(h))
        m = 1;
        return
    end
    D = GRAPH_MAGIC.graphs{g.idx}.array - GRAPH_MAGIC.graphs{h.idx}.array;
    m = nnz(D)>0;
    return
end
m = nnz(GRAPH_MAGIC.graphs{g.idx}.array)/2;