Description of omega
Home > matgraph > @graph > omega.m
omega
PURPOSE
[w,S] = omega(g) --- clique number
SYNOPSIS
function [w,S] = omega(g)
DESCRIPTION
 [w,S] = omega(g) --- clique number
 Returns w, the size of a largest clique, and S, a largest clique.
 Note: Uses integer programming so may run slowly (if at all) on larger
 graphs.
 REQUIRES THE OPTIMIZATION TOOLBOX
CROSS-REFERENCE INFORMATION
This function calls:
alpha [a,S] = alpha(g) --- indepencence number
complement graph complement
copy copy(g,h) --- overwrite g with a copy of h
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
This function is called by:
SOURCE CODE
function [w,S] = omega(g)
% [w,S] = omega(g) --- clique number
% Returns w, the size of a largest clique, and S, a largest clique.
% Note: Uses integer programming so may run slowly (if at all) on larger
% graphs.
%
% REQUIRES THE OPTIMIZATION TOOLBOX
% Note: Our implementation is simply alpha(-g).
h = graph;
copy(h,g);
complement(h);
[w,S] = alpha(h);
free(h);