Description of path
Home > matgraph > @graph > path.m
path
PURPOSE
path(g,n) --- make g a path on n vertices
SYNOPSIS
function path(g,n)
DESCRIPTION
 path(g,n) --- make g a path on n vertices
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
embed embed --- create an embedding for a graph
hasxy hasxy(g) --- determine if an embedding has been created for g
resize resize(g,n) --- change the number of vertices in g to n
rmxy rmxy(g) --- erase g's embedding
This function is called by:
cube cube(g,k) --- create a k-cube (default k = 3)
cycle cycle(g,n) --- create a cycle graph on n vertices
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
SOURCE CODE
function path(g,n)
% path(g,n) --- make g a path on n vertices
if hasxy(g)
    rmxy(g)
end
resize(g,0);
resize(g,n);
for k=1:n-1
    add(g,k,k+1);
end
x = 0:n-1;
y = zeros(1,n);
xy = [x',y'];
embed(g,xy);