Description of prufer
Home > matgraph > @graph > prufer.m
prufer
PURPOSE
prufer --- convert a tree to/from its Prufer code
SYNOPSIS
function output = prufer(g, code)
DESCRIPTION
 prufer --- convert a tree to/from its Prufer code
 output = prufer(g) returns the Prufer code for g (assuming g is a tree)
 prufer(g,code) overwrites g with a tree based on the code
 The Prufer code is a way to map bijectively trees on n vertices
 into n-2 long sequences of integers drawn from [n].
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
copy copy(g,h) --- overwrite g with a copy of h
deg deg: degree of a vertex or degree sequence
delete delete --- delete vertices or edges from a graph
edges edges(g) --- list the edges in g as a 2-column matrix
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
isconnected isconnected(g) --- test if g is a connected graph
ne ne(g) --- number of edges in g or ne(g,h) --- check for inequality
neighbors neighbors(g,v) --- neighbors of v as a list.
nv nv(g) --- number of vertices in g
resize resize(g,n) --- change the number of vertices in g to n
This function is called by:
SUBFUNCTIONS
function ok = prufer_check(list)
SOURCE CODE
function output = prufer(g, code)
% prufer --- convert a tree to/from its Prufer code
% output = prufer(g) returns the Prufer code for g (assuming g is a tree)
% prufer(g,code) overwrites g with a tree based on the code
%
% The Prufer code is a way to map bijectively trees on n vertices
% into n-2 long sequences of integers drawn from [n].
if nargin==1
    n = nv(g);
    m = ne(g);
    if (m ~= n-1)
        error('Input graph is not a tree')
    end
    if (~isconnected(g))
        error('Input graph is not a tree')
    end
    if (n < 2)
        error('Algorithm applies only to trees with 2 or more vertices')
    end
    if (n==2)
        output=[];
        return
    end
    t = graph;  % temporary copy of g
    copy(t,g);
    names = 1:n;  % names of the vertices
    output = zeros(1,n-2);
    for i=1:n-2
        % find least leaf
        d = deg(t);
        v = min(find(d==1));
        % find neighbor of the least leaf
        w = neighbors(t,v);
        output(i) = names(w); % add this vertex to the output
        % delete v and its name
        delete(t,v);
        names = [names(1:v-1),names(v+1:end)];
    end
    free(t)
    return
end
if ~prufer_check(code)
    error('Input is not a valid Prufer code')
end
n = length(code) + 2;
resize(g,0);
resize(g,n);
verts = 1:n;
edges = zeros(n-1,2);
for k=1:n-2
    u = min(setdiff(verts,code));
    v = code(1);
    e = [u,v];
    edges(k,:) = e;
    code = code(2:end);
    i = find(verts == u);
    verts = [verts(1:i-1),verts(i+1:end)];
end
edges(n-1,:) = verts;
add(g,edges);
function ok = prufer_check(list)  % check if list is a valid Prufer code
ok = false;
n = length(list)+2;
if (any(list > n)) || (any(list < 1)) || (any(list ~= round(list)))
    return
end
ok = true;