Description of random_planar
Home > matgraph > @graph > random_planar.m
random_planar
PURPOSE
random_planar(g,n) --- create a random planar triangulation
SYNOPSIS
function random_planar(g,n)
DESCRIPTION
 random_planar(g,n) --- create a random planar triangulation
 This does NOT create a random "uniform" triangulation. Rather, it places
 n points at random in the plane and builds the Delaunay triangulation
 thereon.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
edges edges(g) --- list the edges in g as a 2-column matrix
embed embed --- create an embedding for a graph
resize resize(g,n) --- change the number of vertices in g to n
size size(g) --- returns [nv,ne] for the graph
This function is called by:
SOURCE CODE
function random_planar(g,n)
% random_planar(g,n) --- create a random planar triangulation
% This does NOT create a random "uniform" triangulation. Rather, it places
% n points at random in the plane and builds the Delaunay triangulation
% thereon.
xy = rand(n,2)*sqrt(n);
resize(g,0)
resize(g,n)
embed(g,xy)
triangles = delaunay(xy(:,1), xy(:,2));
nt = size(triangles,1);
edges = [triangles(:,1:2); triangles(:,2:3); triangles(:,[1,3])];
edges = sortrows(edges);
edges = unique(edges,'rows');
add(g,edges)