Description of renumber
Home > matgraph > @graph > renumber.m
renumber
PURPOSE
renumber the vertices of a graph
SYNOPSIS
function renumber(g,perm)
DESCRIPTION
 renumber the vertices of a graph
 renumber(g,perm) --- renumber the vertices of a graph accoring to a
 permutation
 renumber(p,part) --- renumber vertices according to a partition.
 perm should be a permutation of 1 through n
 the graph's vertices are permutated so that the old vertex 1 is now
 vertex perm(1), etc.
 Note: perm may be either an array containing the permutation or a
 permutation object.
 part should be a partition of [n]. We renumber so vertices in the same
 block of the partition are consecutive.
CROSS-REFERENCE INFORMATION
This function calls:
embed embed --- create an embedding for a graph
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
hasxy hasxy(g) --- determine if an embedding has been created for g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
make_logical make_logical(g) --- ensure that the internal storage for g's matrix is a
nv nv(g) --- number of vertices in g
This function is called by:
interval_graph interval_graph(g,ilist) --- create an interval graph
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
random_tree random_tree(t,n) --- overwrite t with a random tree on n vertices
SUBFUNCTIONS
function list = partition2list(p)
SOURCE CODE
function renumber(g,perm)
% renumber the vertices of a graph
% renumber(g,perm) --- renumber the vertices of a graph accoring to a
% permutation
% renumber(p,part) --- renumber vertices according to a partition.
%
% perm should be a permutation of 1 through n
% the graph's vertices are permutated so that the old vertex 1 is now
% vertex perm(1), etc.
% Note: perm may be either an array containing the permutation or a
% permutation object.
%
% part should be a partition of [n]. We renumber so vertices in the same
% block of the partition are consecutive.
global GRAPH_MAGIC
n = nv(g);
if isa(perm,'partition')
    perm = partition2list(perm);
end
if ~isa(perm,'permutation')
    perm = permutation(perm);
end
if length(perm) ~= n
    error('Length of permutation does not match size of graph')
end
perm = inv(perm);
q = array(perm);
GRAPH_MAGIC.graphs{g.idx}.array = ...
    GRAPH_MAGIC.graphs{g.idx}.array(q,q);
make_logical(g);
if hasxy(g)
    xy = getxy(g);
    xy = xy(q,:);
    embed(g,xy);
end
if is_labeled(g)
    tmp = cell(n,1);
    for k=1:n
        tmp{k} = GRAPH_MAGIC.graphs{g.idx}.labels{perm(k)};
    end
    GRAPH_MAGIC.graphs{g.idx}.labels = tmp;
end
function list = partition2list(p)
pp = parts(p);
list = [];
for k=1:np(p)
    list = [list, pp{k}];
end