Description of resize
Home > matgraph > @graph > resize.m
resize
PURPOSE
resize(g,n) --- change the number of vertices in g to n
SYNOPSIS
function resize(g, n)
DESCRIPTION
 resize(g,n) --- change the number of vertices in g to n
 note: if n is less than nv(g), vertices will be lost
 if the graph has an embedding, all new vertices are sited at the origin.
CROSS-REFERENCE INFORMATION
This function calls:
hasxy hasxy(g) --- determine if an embedding has been created for g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
isfull isfull(g) --- check if g's adjacency matrix is full
make_logical make_logical(g) --- ensure that the internal storage for g's matrix is a
nv nv(g) --- number of vertices in g
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
add add --- add edge(s) to the graph
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
cayley cayley(g,perms) -- create a Cayley graph (undirected)
circulant circulant(g,n,k) --- overwrite g with an n,k circulant graph
cube cube(g,k) --- create a k-cube (default k = 3)
dodecahedron dodecahedron(g) --- overwrite g with the dodecahedron graph
fgraph fgraph(g,n,func) -- create a graph based on a function.
grid grid(g,a,b) --- create an a-by-b grid graph
icosahedron icosahedron(g) --- overwrite g with the icosahedron graph
intersect intersect(g,h1,h2) --- g is set to the intersection of h1 and h2.
interval_graph interval_graph(g,ilist) --- create an interval graph
line_graph line_graph(g,h) --- set g to be the line graph of h
load load(g,filename) --- read a saved graph on disk
octahedron octahedron(g) --- overwrite g with the octahedron graph, K(2,2,2)
paley paley(g,n) --- create a Paley graph with n vertices
path path(g,n) --- make g a path on n vertices
petersen petersen(g) --- overwrite g with the Petersen graph
prufer prufer --- convert a tree to/from its Prufer code
random_planar random_planar(g,n) --- create a random planar triangulation
random_tree random_tree(t,n) --- overwrite t with a random tree on n vertices
selective selective(g,n,n0,d) --- selective attachment random graph
sgf sgf --- simple graph format: a 2-column matrix representation
shiftgraph shiftgraph(g,k,t) -- create a shiftgraph g based on t-tuples of k symbols
sl2graph sl2graph(g,p) -- create an SL(2,p) graph
union union(g,h1,h2) --- set g equal to the union of h1 and h2.
wheel wheel(g,n) --- overwrite g with a wheel graph on n vertices
SOURCE CODE
function resize(g, n)
% resize(g,n) --- change the number of vertices in g to n
% note: if n is less than nv(g), vertices will be lost
% if the graph has an embedding, all new vertices are sited at the origin.
old_n = nv(g);
if (n == old_n)   % no change
    return
end
global GRAPH_MAGIC
if (n < old_n)    % shrink
    GRAPH_MAGIC.graphs{g.idx}.array = ...
        GRAPH_MAGIC.graphs{g.idx}.array(1:n,1:n);
    make_logical(g);
    if hasxy(g)
        GRAPH_MAGIC.graphs{g.idx}.xy = ...
            GRAPH_MAGIC.graphs{g.idx}.xy(1:n,:);
    end
    if is_labeled(g)
        GRAPH_MAGIC.graphs{g.idx}.labels = ...
            GRAPH_MAGIC.graphs{g.idx}.labels(1:n);
    end
    return
end
% we need to add extra zeros to g's adjacency matrix. we decide what to do
% based on g's storage class.
if (isfull(g))
    A = zeros(old_n, n-old_n);
    B = zeros(n-old_n, n-old_n);
else
    A = sparse([],[],[],old_n,n-old_n);
    B = sparse([],[],[],n-old_n,n-old_n);
end
if hasxy(g)
    morexy = zeros(n-old_n,2);
    GRAPH_MAGIC.graphs{g.idx}.xy = ...
        [GRAPH_MAGIC.graphs{g.idx}.xy; morexy];
end
if is_labeled(g)
    newlabels = cell(n,1);
    for k=1:old_n
        newlabels{k} = GRAPH_MAGIC.graphs{g.idx}.labels{k};
    end
    for k=(old_n+1):n
        newlabels{k} = int2str(k);
    end
    GRAPH_MAGIC.graphs{g.idx}.labels = newlabels;
end
GRAPH_MAGIC.graphs{g.idx}.array = ...
    [GRAPH_MAGIC.graphs{g.idx}.array, A; A', B];
make_logical(g);