Description of rmxy
Home > matgraph > @graph > rmxy.m
rmxy
PURPOSE
rmxy(g) --- erase g's embedding
SYNOPSIS
function rmxy(g)
DESCRIPTION
 rmxy(g) --- erase g's embedding
CROSS-REFERENCE INFORMATION
This function calls:
hasxy hasxy(g) --- determine if an embedding has been created for g
This function is called by:
disjoint_union disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
interval_graph interval_graph(g,ilist) --- create an interval graph
join join(g,h1,h2) --- overwrite g with the join of h1 and h2
line_graph line_graph(g,h) --- set g to be the line graph of h
mobius mobius(g,nverts) --- create a Mobius ladder graph
mycielski mycielski(g,n) --- create n'th order Mycielski graph (n > 0)
paley paley(g,n) --- create a Paley graph with n vertices
path path(g,n) --- make g a path on n vertices
random_bipartite random_bipartite(g,n,m,p) --- create a random bipartite graph
random_regular random_regular(g,n,k) --- create a random regular graph
selective selective(g,n,n0,d) --- selective attachment random graph
sprandom sprandom(g,n,p) --- create a sparse random graph
SOURCE CODE
function rmxy(g)
% rmxy(g) --- erase g's embedding
global GRAPH_MAGIC
if hasxy(g)
    GRAPH_MAGIC.graphs{g.idx} = rmfield(GRAPH_MAGIC.graphs{g.idx},'xy');
end