Description of scale
Home > matgraph > @graph > scale.m
scale
PURPOSE
scale(g,s) --- rescale the embedding of g by s
SYNOPSIS
function scale(g,s)
DESCRIPTION
 scale(g,s) --- rescale the embedding of g by s
CROSS-REFERENCE INFORMATION
This function calls:
embed embed --- create an embedding for a graph
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
hasxy hasxy(g) --- determine if an embedding has been created for g
This function is called by:
graffle graffle(g, filename, width, rad) --- write graph in OmniGraffle format
SOURCE CODE
function scale(g,s)
% scale(g,s) --- rescale the embedding of g by s
if ~hasxy(g)
    embed(g)
end
xy = getxy(g);
xy = s*xy;
embed(g,xy);