Description of set_matrix
Home > matgraph > @graph > set_matrix.m
set_matrix
PURPOSE
set_matrix(g,A) --- set g to be the graph specificed in the matrix A.
SYNOPSIS
function set_matrix(g,A)
DESCRIPTION
 set_matrix(g,A) --- set g to be the graph specificed in the matrix A.
 The matrix is scanned by check_matrix to be sure it is a valid adjacency
 matrix. If it is not, an error is triggered and the graph is left
 unchanged.
CROSS-REFERENCE INFORMATION
This function calls:
fast_set_matrix fast_set_matrix(g,A) --- overwrite the adjacency matrix of g with A
This function is called by:
bucky bucky(g) --- overwrite g with the Buckyball graph (and give a nice
fgraph fgraph(g,n,func) -- create a graph based on a function.
match_join match_join(g,h1,h2) --- overwrite g with a graph formed from disjoint
thresh create a threshold graph, or test if g is a threshold graph
SOURCE CODE
function set_matrix(g,A)
% set_matrix(g,A) --- set g to be the graph specificed in the matrix A.
% The matrix is scanned by check_matrix to be sure it is a valid adjacency
% matrix. If it is not, an error is triggered and the graph is left
% unchanged.
if (~check_matrix(A))
    error('Input matrix is not a valid adjacency matrix')
end
fast_set_matrix(g,logical(A));