Description of sparse
Home > matgraph > @graph > sparse.m
sparse
PURPOSE
sparse(g) --- convert internal storage for g to sparse
SYNOPSIS
function sparse(g)
DESCRIPTION
 sparse(g) --- convert internal storage for g to sparse
CROSS-REFERENCE INFORMATION
This function calls:
sparse sparse(g) --- convert internal storage for g to sparse
This function is called by:
add add --- add edge(s) to the graph
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
clear_edges clear_edges(g) --- delete all edges of g
disjoint_union disjoint_union(g,h,k) --- overwrite g with the disjoint union of the
graph graph: constructor for the graph class
incidence_matrix incidence_matrix(g) --- return the vertex/edge incidence matrix.
load load(g,filename) --- read a saved graph on disk
resize resize(g,n) --- change the number of vertices in g to n
sgf sgf --- simple graph format: a 2-column matrix representation
shiftgraph shiftgraph(g,k,t) -- create a shiftgraph g based on t-tuples of k symbols
sl2graph sl2graph(g,p) -- create an SL(2,p) graph
sparse sparse(g) --- convert internal storage for g to sparse
SOURCE CODE
function sparse(g)
% sparse(g) --- convert internal storage for g to sparse
global GRAPH_MAGIC
GRAPH_MAGIC.graphs{g.idx}.array = ...
    sparse(GRAPH_MAGIC.graphs{g.idx}.array);