Description of trim
Home > matgraph > @graph > trim.m
trim
PURPOSE
trim(g,d) --- iteratively remove vertices of degree at most d
SYNOPSIS
function trim(g,d)
DESCRIPTION
 trim(g,d) --- iteratively remove vertices of degree at most d
CROSS-REFERENCE INFORMATION
This function calls:
deg deg: degree of a vertex or degree sequence
delete delete --- delete vertices or edges from a graph
nv nv(g) --- number of vertices in g
This function is called by:
SOURCE CODE
function trim(g,d)
% trim(g,d) --- iteratively remove vertices of degree at most d
if nargin==1
    d = 0;
end
ds = deg(g);
x = find(ds <= d);
x=x';
while (length(x) > 0)
    if (nv(g) == 0)
        return
    end
    delete(g,x);
    ds = deg(g);
    x = find(ds <= d);
    x=x';
end