Description of uminus
Home > matgraph > @graph > uminus.m
uminus
PURPOSE
uminus(g) --- operator form of complement: h = -g;
SYNOPSIS
function h = uminus(g)
DESCRIPTION
 uminus(g) --- operator form of complement: h = -g;
 WARNING: creates a new graph
 THIS FUNCTION IS STRONGLY DEPROCATED. I PLAN TO REMOVE IT FROM MATGRAPH.
CROSS-REFERENCE INFORMATION
This function calls:
complement graph complement
copy copy(g,h) --- overwrite g with a copy of h
graph graph: constructor for the graph class
This function is called by:
SOURCE CODE
function h = uminus(g)
% uminus(g) --- operator form of complement: h = -g;
% WARNING: creates a new graph
% THIS FUNCTION IS STRONGLY DEPROCATED. I PLAN TO REMOVE IT FROM MATGRAPH.
h = graph;
copy(h,g);
complement(h);