Description of wheel
Home > matgraph > @graph > wheel.m
wheel
PURPOSE
wheel(g,n) --- overwrite g with a wheel graph on n vertices
SYNOPSIS
function wheel(g,n)
DESCRIPTION
 wheel(g,n) --- overwrite g with a wheel graph on n vertices
 if n is omitted, we use the number of vertices in g
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
cycle cycle(g,n) --- create a cycle graph on n vertices
nv nv(g) --- number of vertices in g
resize resize(g,n) --- change the number of vertices in g to n
This function is called by:
SOURCE CODE
function wheel(g,n)
% wheel(g,n) --- overwrite g with a wheel graph on n vertices
% if n is omitted, we use the number of vertices in g
if (nargin == 1)
    n = nv(g);
end
cycle(g,n-1);
resize(g,n);
for k=1:n-1
    add(g,k,n);
end