Description of graph_system_exists
Home > matgraph > graph_system_exists.m
graph_system_exists
PURPOSE
graph_system_exists checks to see if the GRAPH_MAGIC global structure has
SYNOPSIS
function tf = graph_system_exists
DESCRIPTION
 graph_system_exists checks to see if the GRAPH_MAGIC global structure has
 been initialized.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
free_all free_all --- delete all graphs from the GRAPH_MAGIC system
graph_init graph_init(capacity) --- used to initialize the GRAPH_MAGIC data
max_available num_available --- maximum number of graphs we can hold in this system
num_available num_available --- number of free slots in the graph system
set_large set_large(n) --- set the cut off size for large graphs.
SOURCE CODE
function tf = graph_system_exists
% graph_system_exists checks to see if the GRAPH_MAGIC global structure has
% been initialized.
tf = ~isempty(whos('global','GRAPH_MAGIC'));