Description of cycles
Home > matgraph > @permutation > cycles.m
cycles
PURPOSE
cycles(p) returns a cell array containing the cycle structure of p
SYNOPSIS
function c = cycles(p)
DESCRIPTION
 cycles(p) returns a cell array containing the cycle structure of p
CROSS-REFERENCE INFORMATION
This function calls:
length length(p) gives the size of the permutation
This function is called by:
display display(p) --- display a permutation in disjoint cycle form.
longest_cycle longest_cycle(p) -- return the length of the longest cycle in p
sign sign of a permutation (1 for even, -1 for odd)
size size(p) returns the number of elements permuted and the number of cycles.
SOURCE CODE
function c = cycles(p)
% cycles(p) returns a cell array containing the cycle structure of p
c = {};
n = length(p);
if n == 0
    return
end
used = zeros(1,n);
count = 0;
while (sum(used)<n)
    count = count + 1;
    avail = find(used == 0);
    i = avail(1);
    current = i;
    used(i) = 1;
    while(true)
        j = p.array(i);
        if used(j)
            break
        else
            current = [current,j];
            i = j;
            used(i)=1;
        end
    end
    c{count} = current;
end