Description of display
Home > matgraph > @permutation > display.m
display
PURPOSE
display(p) --- display a permutation in disjoint cycle form.
SYNOPSIS
function st = display(p)
DESCRIPTION
 display(p) --- display a permutation in disjoint cycle form.
CROSS-REFERENCE INFORMATION
This function calls:
cycles cycles(p) returns a cell array containing the cycle structure of p
isempty isempty(p) --- check if the permutation p is of size 0
length length(p) gives the size of the permutation
This function is called by:
SUBFUNCTIONS
function str = list_to_cycle(list)
SOURCE CODE
function st = display(p)
% display(p) --- display a permutation in disjoint cycle form.
% special case if the permutation is empty
if isempty(p)
    st= '()';
    if nargout == 0
        disp(st)
    end
    return
end
c = cycles(p);
outstr = '';
for k=1:length(c)
    outstr = [outstr,list_to_cycle(c{k})];
end
if nargout > 0
    st = outstr;
else
    disp(outstr)
end
function str = list_to_cycle(list)
if isempty(list)
    str = '()';
    return
end
str = '(';
for k=1:length(list)
    str = [str,int2str(list(k))];
    if k < length(list)
        str = [str,','];
    else
        str = [str,')'];
    end
end