Description of np
Home > matgraph > @partition > np.m
np
PURPOSE
np(p) --- number of parts in the partition p
SYNOPSIS
function m = np(p)
DESCRIPTION
 np(p) --- number of parts in the partition p
CROSS-REFERENCE INFORMATION
This function calls:
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
merge merge(p,x,y) --- form a partition from p by combining x and y's parts.
mtimes mtimes(p,q) --- p*q is the meet of the partitions p and q
SOURCE CODE
function m = np(p)
% np(p) --- number of parts in the partition p
m = size(p.array,1);