(TeX-add-style-hook "by-example"
 (function
  (lambda ()
    (LaTeX-add-labels
     "sect:download"
     "sect:first-session"
     "fig:petersen"
     "fig:petersen-vertex"
     "fig:grid34"
     "fig:randtree"
     "fig:labeled-path"
     "sect:ops"
     "fig:product-graph"
     "fig:bfstree"
     "fig:ham-cycle"
     "fig:bucky"
     "fig:split-grid"
     "sect:sgf"
     "fig:star"
     "fig:parsed"
     "fig:four-cube"
     "fig:graffle")
    (TeX-add-symbols
     "matlab"
     "matgraph"
     "ER"
     "RR"
     "ZZ")
    (TeX-run-style-hooks
     "graphicx"
     "geometry"
     "margin=1in"
     "hyperref"
     "courier"
     "mathptmx"
     "times"
     "superdate"
     "latex2e"
     "amsart12"
     "amsart"
     "12pt"))))

